sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t udeshyagiri/my-kanban-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udeshyagiri/my-kanban-client npm run test
